import type { Metadata } from "next";
import { ManageHeader } from "@/components/ManageHeader/ManageHeader";

export const metadata: Metadata = {
  title: "Ogame's Page Manage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <ManageHeader />
      <div style={{height: "12vh"}}/>
      {children}
    </div>
  );
}
