version: "3.9"
services:
  mypage:
    image: node:18
    command: /root/product/execute.sh
    container_name: mypage
    volumes:
      - .:/root/product
    ports:
      - "3000:3000"
    networks:
      - app-net
  db:
    image: postgres
    container_name: mypage_database
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app-net

networks:
  app-net:
    name: mypage_app_net
    driver: bridge

volumes:
  dbdata: null
