import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";

const robotoMono = Roboto_Mono({
  weight: "400",
  style: "normal",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Ogame's Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoMono.className}`}>
        {children}
      </body>
    </html>
  );
}
